### ISSUE TITLE
NEXTION - hotend2 and bed icon 

### ISSUE THREAD

**Issue by jgauchia** [MagoKimbra/MarlinKimbra#107]
It's possible if the board doesn't have heated bed or hotend2 (like BOARD_RAMPS_13_HHF )display no icon in Nextion screen?

Visually looks better. 
Thank you!

**Comment by MagoKimbra** [comment]
In the latest version it is so.

**Comment by jgauchia** [comment]
Ok thank you!

**Comment by Deepoff** [comment]
change the picture when screen is initialized to a blank (background)

**Comment by jgauchia** [comment]
Works fine in latest version.
