### ISSUE TITLE
error : sd card init

### ISSUE THREAD

**Issue by prophetmaster** [MagoKimbra/MarlinKimbra#108]
message to serial on connect : 

I have ramps 1.4 and in Configuration_Feature.h

#define SDSUPPORT
#define SD_DISABLED_DETECT
//#define SD_DETECT_INVERTED
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

on connect i get this error: SD card init fail...

**Comment by MagoKimbra** [comment]
If enabled SD DETECT DISABLED firmware no longer controls the insertion pin SD and assumes that it is always on, so when he goes to read and can not find it by mistake.

**Comment by prophetmaster** [comment]
I tested and not it does not work!

**Comment by MagoKimbra** [comment]
Excuse me, I explained wrong ... it is normal that if it do not find sd give error. Because for the firmware the SD is always inside.

**Comment by prophetmaster** [comment]
this makes little sense as a way to ... well how do we make it work?

**Comment by MagoKimbra** [comment]
Some sd readers do not have the pin to check if the sd is inserted or not.
So you have to force the firmware to believe that it is always in, but if it is not inserted give error.
If your sd reader has the pin disable SD_DISABLED_DETECT

**Comment by prophetmaster** [comment]
I tested all possible solutions nothing works ...

**Comment by MagoKimbra** [comment]
Is Sd formatted FAT? The reader function?

**Comment by prophetmaster** [comment]
my sdcard is dead i have tested another and no bug... excuse me for the issue

**Comment by MagoKimbra** [comment]
No problem...
