### ISSUE TITLE
Wrong output on M105

### ISSUE THREAD

**Issue by repetier** [MagoKimbra/MarlinKimbra#119]
Your output to M105 is wrong. It looks like this:

< 17:44:02.233: N4054 M105
> 17:44:02.245: ok T:21.1 /0.0 B:23.0 /0.0 T:21.1 /0.0 T:22.8 /0.0 B@:0 @:0 @:0 @:0

The second T: has a 0 byte between T and : where you wanted to add a "0" char. Same with @1: which is written as "@"+chr(1)+":". So you always forget to add the offset for zero char. That causes problems for parsers. In C it would even cut the string at the first chr(0). This prevents host from correctly parsing the temperatures.

**Comment by MagoKimbra** [comment]
Thank's
I see to fix it!!!

**Comment by repetier** [comment]
Looks much better now. Just a tine thing I noted that you output

okT

should be
ok T

**Comment by MagoKimbra** [comment]
Yes i know... This night i correct It... 
Il 27/Apr/2016 17:16, repetier <notifications@github.com> ha scritto:Looks much better now. Just a tine thing I noted that you output

okT

should be
ok T

**Comment by MagoKimbra** [comment]
Fix!!
