### ISSUE TITLE
Filament runout error

### ISSUE THREAD

**Issue by Dougwar** [MagoKimbra/MarlinKimbra#121]
I'm using the feature filament runout, I use pin 2, and I can see it being triggered and not triggered in pronterface (m119), but when I'm printing something for test nothing happens when the sensor is not triggered
Thanks

**Comment by MagoKimbra** [comment]
For activate filament runout during print you must use M11 to start gcode...

**Comment by Dougwar** [comment]
thank you for the prompt reply
