### ISSUE TITLE
ERROR !!

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#124]
Arduino: 1.6.7 (Mac OS X), Placa:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch/base.h:48:0,
                 from sketch/Configuration_Store.cpp:1:
sketch/module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/base.h:48:0,
                 from /Users/brenosouza/Downloads/MarlinKimbra-master-38/MK/MK.ino:198:
sketch/module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/../base.h:48:0,
                 from sketch/module/MK_Main.cpp:31:
sketch/module/../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/HAL/../../base.h:48:0,
                 from sketch/module/HAL/HAL.cpp:57:
sketch/module/HAL/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/HAL/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/HAL/../../base.h:48:0,
                 from sketch/module/HAL/HardwareSerial.cpp:23:
sketch/module/HAL/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/HAL/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/blinkm/../../base.h:48:0,
                 from sketch/module/blinkm/blinkm.cpp:28:
sketch/module/blinkm/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/blinkm/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/digipot/../../base.h:48:0,
                 from sketch/module/digipot/digipot_mcp4451.cpp:1:
sketch/module/digipot/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/digipot/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/fwtest/../../base.h:48:0,
                 from sketch/module/fwtest/firmware_test.cpp:23:
sketch/module/fwtest/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/fwtest/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/lcd/../../base.h:48:0,
                 from sketch/module/lcd/buzzer.cpp:23:
sketch/module/lcd/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/lcd/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/lcd/../../base.h:48:0,
                 from sketch/module/lcd/ultralcd.cpp:23:
sketch/module/lcd/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/lcd/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
sketch/module/lcd/ultralcd.cpp: In function 'void _lcd_babystep(int, const char*)':
sketch/module/lcd/ultralcd.cpp:640:83: error: 'itostr3sign' was not declared in this scope
     if (lcdDrawUpdate) lcd_implementation_drawedit(msg, itostr3sign(babysteps_done));
                                                                                   ^
exit status 1
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
I fix it!
