### ISSUE TITLE
ERROR 2!!

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#125]
Arduino: 1.6.7 (Mac OS X), Placa:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch/base.h:48:0,
                 from sketch/Configuration_Store.cpp:1:
sketch/module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/base.h:48:0,
                 from /Users/brenosouza/Downloads/MarlinKimbra-master-38/MK/MK.ino:198:
sketch/module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/../base.h:48:0,
                 from sketch/module/MK_Main.cpp:31:
sketch/module/../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/HAL/../../base.h:48:0,
                 from sketch/module/HAL/HAL.cpp:57:
sketch/module/HAL/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/HAL/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/HAL/../../base.h:48:0,
                 from sketch/module/HAL/HardwareSerial.cpp:23:
sketch/module/HAL/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/HAL/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/blinkm/../../base.h:48:0,
                 from sketch/module/blinkm/blinkm.cpp:28:
sketch/module/blinkm/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/blinkm/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/digipot/../../base.h:48:0,
                 from sketch/module/digipot/digipot_mcp4451.cpp:1:
sketch/module/digipot/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/digipot/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/fwtest/../../base.h:48:0,
                 from sketch/module/fwtest/firmware_test.cpp:23:
sketch/module/fwtest/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/fwtest/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/lcd/../../base.h:48:0,
                 from sketch/module/lcd/buzzer.cpp:23:
sketch/module/lcd/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/lcd/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/lcd/../../base.h:48:0,
                 from sketch/module/lcd/ultralcd.cpp:23:
sketch/module/lcd/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/lcd/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/lcd/../../base.h:50:0,
                 from sketch/module/lcd/ultralcd.cpp:23:
sketch/module/lcd/../../module/MK_Main.h:54:15: warning: 'void calculate_delta(float*)' used but never defined [enabled by default]
   static void calculate_delta(float cartesian[3]);
               ^
In file included from sketch/module/motion/../../base.h:48:0,
                 from sketch/module/motion/cartesian_correction.cpp:46:
sketch/module/motion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/motion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/motion/../../base.h:48:0,
                 from sketch/module/motion/planner.cpp:73:
sketch/module/motion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/motion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/motion/../../base.h:48:0,
                 from sketch/module/motion/qr_solve.cpp:23:
sketch/module/motion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/motion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/motion/../../base.h:48:0,
                 from sketch/module/motion/stepper.cpp:48:
sketch/module/motion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/motion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/motion/../../base.h:48:0,
                 from sketch/module/motion/stepper_indirection.cpp:31:
sketch/module/motion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/motion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/motion/../../base.h:48:0,
                 from sketch/module/motion/vector_3.cpp:42:
sketch/module/motion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/motion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexButton.h:20,
                 from sketch/module/nextion/NexButton.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexCrop.h:20,
                 from sketch/module/nextion/NexCrop.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexDualStateButton.h:21,
                 from sketch/module/nextion/NexDualStateButton.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexGauge.h:20,
                 from sketch/module/nextion/NexGauge.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexHardware.h:19,
                 from sketch/module/nextion/NexHardware.cpp:15:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
sketch/module/nextion/NexHardware.cpp: In function 'bool recvRetNumber(uint32_t*, uint32_t)':
sketch/module/nextion/NexHardware.cpp:68:31: warning: left shift count >= width of type [enabled by default]
         *number = (temp[4] << 24) | (temp[3] << 16) | (temp[2] << 8) | (temp[1]);
                               ^
sketch/module/nextion/NexHardware.cpp:68:49: warning: left shift count >= width of type [enabled by default]
         *number = (temp[4] << 24) | (temp[3] << 16) | (temp[2] << 8) | (temp[1]);
                                                 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexHotspot.h:20,
                 from sketch/module/nextion/NexHotspot.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexNumber.h:20,
                 from sketch/module/nextion/NexNumber.cpp:15:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexObject.h:20,
                 from sketch/module/nextion/NexObject.cpp:15:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexPage.h:20,
                 from sketch/module/nextion/NexPage.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexPicture.h:20,
                 from sketch/module/nextion/NexPicture.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexProgressBar.h:20,
                 from sketch/module/nextion/NexProgressBar.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexSlider.h:20,
                 from sketch/module/nextion/NexSlider.cpp:15:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexText.h:20,
                 from sketch/module/nextion/NexText.cpp:15:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexTimer.h:20,
                 from sketch/module/nextion/NexTimer.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexTouch.cpp:15:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexHardware.h:19,
                 from sketch/module/nextion/NexUpload.h:20,
                 from sketch/module/nextion/NexUpload.cpp:16:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexVar.h:20,
                 from sketch/module/nextion/NexVar.cpp:15:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/NexConfig.h:16,
                 from sketch/module/nextion/NexTouch.h:21,
                 from sketch/module/nextion/NexWaveform.h:19,
                 from sketch/module/nextion/NexWaveform.cpp:15:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/Nextion_gfx.cpp:18:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/nextion/../../base.h:48:0,
                 from sketch/module/nextion/Nextion_lcd.cpp:42:
sketch/module/nextion/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/nextion/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/sd/../../base.h:48:0,
                 from sketch/module/sd/SDFat.cpp:44:
sketch/module/sd/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/sd/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/sd/../../base.h:48:0,
                 from sketch/module/sd/cardreader.cpp:23:
sketch/module/sd/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/sd/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/servo/../../base.h:48:0,
                 from sketch/module/servo/servo.cpp:41:
sketch/module/servo/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/servo/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/stopwatch/../../base.h:48:0,
                 from sketch/module/stopwatch/stopwatch.cpp:23:
sketch/module/stopwatch/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/stopwatch/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/temperature/../../base.h:48:0,
                 from sketch/module/temperature/temperature.cpp:43:
sketch/module/temperature/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/temperature/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/watchdog/../../base.h:48:0,
                 from sketch/module/watchdog/watchdog.cpp:23:
sketch/module/watchdog/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/watchdog/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
sketch/module/lcd/ultralcd.cpp.o: In function `lcd_extrude':
sketch/module/lcd/ultralcd.cpp:800: undefined reference to `calculate_delta(float*)'
sketch/module/lcd/ultralcd.cpp.o: In function `line_to_current(AxisEnum)':
sketch/module/lcd/ultralcd.cpp:510: undefined reference to `calculate_delta(float*)'
collect2: error: ld returned 1 exit status
exit status 1
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
i fix it!
