### ISSUE TITLE
ERROR 5

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#128]
Arduino: 1.6.7 (Mac OS X), Placa:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch/base.h:48:0,
                 from sketch/Configuration_Store.cpp:1:
sketch/module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/base.h:48:0,
                 from /Users/brenosouza/Downloads/MarlinKimbra-master-41/MK/MK.ino:198:
sketch/module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/../base.h:48:0,
                 from sketch/module/MK_Main.cpp:31:
sketch/module/../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/HAL/../../base.h:48:0,
                 from sketch/module/HAL/HAL.cpp:57:
sketch/module/HAL/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/HAL/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/HAL/../../base.h:48:0,
                 from sketch/module/HAL/HardwareSerial.cpp:23:
sketch/module/HAL/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/HAL/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/blinkm/../../base.h:48:0,
                 from sketch/module/blinkm/blinkm.cpp:28:
sketch/module/blinkm/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/blinkm/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/digipot/../../base.h:48:0,
                 from sketch/module/digipot/digipot_mcp4451.cpp:1:
sketch/module/digipot/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/digipot/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/fwtest/../../base.h:48:0,
                 from sketch/module/fwtest/firmware_test.cpp:23:
sketch/module/fwtest/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/fwtest/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/lcd/../../base.h:48:0,
                 from sketch/module/lcd/buzzer.cpp:23:
sketch/module/lcd/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/lcd/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/lcd/../../base.h:48:0,
                 from sketch/module/lcd/ultralcd.cpp:23:
sketch/module/lcd/../../module/language/language.h:130:0: warning: "SERIAL_COUNT_X" redefined [enabled by default]
 #define SERIAL_COUNT_X                          " Count X:"
 ^
sketch/module/lcd/../../module/language/language.h:120:0: note: this is the location of the previous definition
 #define SERIAL_COUNT_X                          " Count X: "
 ^
In file included from sketch/module/lcd/ultralcd.cpp:87:0:
sketch/module/lcd/ultralcd.cpp: In function 'void lcd_control_temperature_menu()':
sketch/module/lcd/ultralcd.cpp:1441:32: error: 'MSG_PID_C' was not declared in this scope
         MENU_ITEM_EDIT(float3, MSG_PID_C HLABEL, &PID_PARAM(Kc, hindex), 1, 9990)
                                ^
sketch/module/lcd/ultralcd_implementation_hitachi_HD44780.h:890:165: note: in definition of macro 'lcd_implementation_drawmenu_setting_edit_float3'
 #define lcd_implementation_drawmenu_setting_edit_float3(sel, row, pstr, pstr2, data, minValue, maxValue) lcd_implementation_drawmenu_setting_edit_generic(sel, row, pstr, '>', ftostr3(*(data)))
                                                                                                                                                                     ^
sketch/module/lcd/ultralcd.cpp:248:7: note: in expansion of macro '_MENU_ITEM_PART_1'
       _MENU_ITEM_PART_1(type, label, ## args); \
       ^
sketch/module/lcd/ultralcd.cpp:269:48: note: in expansion of macro 'MENU_ITEM'
   #define MENU_ITEM_EDIT(type, label, args...) MENU_ITEM(setting_edit_ ## type, label, PSTR(label), ## args)
                                                ^
sketch/module/lcd/ultralcd.cpp:1441:9: note: in expansion of macro 'MENU_ITEM_EDIT'
         MENU_ITEM_EDIT(float3, MSG_PID_C HLABEL, &PID_PARAM(Kc, hindex), 1, 9990)
         ^
sketch/module/lcd/ultralcd.cpp:1451:46: note: in expansion of macro '_PID_MENU_ITEMS'
       #define PID_MENU_ITEMS(HLABEL, hindex) _PID_MENU_ITEMS(HLABEL, hindex)
                                              ^
sketch/module/lcd/ultralcd.cpp:1454:5: note: in expansion of macro 'PID_MENU_ITEMS'
     PID_MENU_ITEMS("", 0);
     ^
sketch/module/lcd/ultralcd.cpp:1454:20: error: expected ')' before string constant
     PID_MENU_ITEMS("", 0);
                    ^
sketch/module/lcd/ultralcd_implementation_hitachi_HD44780.h:890:165: note: in definition of macro 'lcd_implementation_drawmenu_setting_edit_float3'
 #define lcd_implementation_drawmenu_setting_edit_float3(sel, row, pstr, pstr2, data, minValue, maxValue) lcd_implementation_drawmenu_setting_edit_generic(sel, row, pstr, '>', ftostr3(*(data)))
                                                                                                                                                                     ^
sketch/module/lcd/ultralcd.cpp:248:7: note: in expansion of macro '_MENU_ITEM_PART_1'
       _MENU_ITEM_PART_1(type, label, ## args); \
       ^
sketch/module/lcd/ultralcd.cpp:269:48: note: in expansion of macro 'MENU_ITEM'
   #define MENU_ITEM_EDIT(type, label, args...) MENU_ITEM(setting_edit_ ## type, label, PSTR(label), ## args)
                                                ^
sketch/module/lcd/ultralcd.cpp:1441:9: note: in expansion of macro 'MENU_ITEM_EDIT'
         MENU_ITEM_EDIT(float3, MSG_PID_C HLABEL, &PID_PARAM(Kc, hindex), 1, 9990)
         ^
sketch/module/lcd/ultralcd.cpp:1451:46: note: in expansion of macro '_PID_MENU_ITEMS'
       #define PID_MENU_ITEMS(HLABEL, hindex) _PID_MENU_ITEMS(HLABEL, hindex)
                                              ^
sketch/module/lcd/ultralcd.cpp:1454:5: note: in expansion of macro 'PID_MENU_ITEMS'
     PID_MENU_ITEMS("", 0);
     ^
sketch/module/lcd/ultralcd.cpp:1441:32: error: 'MSG_PID_C' was not declared in this scope
         MENU_ITEM_EDIT(float3, MSG_PID_C HLABEL, &PID_PARAM(Kc, hindex), 1, 9990)
                                ^
sketch/module/lcd/ultralcd.cpp:241:30: note: in definition of macro '_MENU_ITEM_PART_2'
         menu_action_ ## type(args); \
                              ^
sketch/module/lcd/ultralcd.cpp:269:48: note: in expansion of macro 'MENU_ITEM'
   #define MENU_ITEM_EDIT(type, label, args...) MENU_ITEM(setting_edit_ ## type, label, PSTR(label), ## args)
                                                ^
sketch/module/lcd/ultralcd.cpp:1441:9: note: in expansion of macro 'MENU_ITEM_EDIT'
         MENU_ITEM_EDIT(float3, MSG_PID_C HLABEL, &PID_PARAM(Kc, hindex), 1, 9990)
         ^
sketch/module/lcd/ultralcd.cpp:1451:46: note: in expansion of macro '_PID_MENU_ITEMS'
       #define PID_MENU_ITEMS(HLABEL, hindex) _PID_MENU_ITEMS(HLABEL, hindex)
                                              ^
sketch/module/lcd/ultralcd.cpp:1454:5: note: in expansion of macro 'PID_MENU_ITEMS'
     PID_MENU_ITEMS("", 0);
     ^
sketch/module/lcd/ultralcd.cpp:1454:20: error: expected ')' before string constant
     PID_MENU_ITEMS("", 0);
                    ^
sketch/module/lcd/ultralcd.cpp:241:30: note: in definition of macro '_MENU_ITEM_PART_2'
         menu_action_ ## type(args); \
                              ^
sketch/module/lcd/ultralcd.cpp:269:48: note: in expansion of macro 'MENU_ITEM'
   #define MENU_ITEM_EDIT(type, label, args...) MENU_ITEM(setting_edit_ ## type, label, PSTR(label), ## args)
                                                ^
sketch/module/lcd/ultralcd.cpp:1441:9: note: in expansion of macro 'MENU_ITEM_EDIT'
         MENU_ITEM_EDIT(float3, MSG_PID_C HLABEL, &PID_PARAM(Kc, hindex), 1, 9990)
         ^
sketch/module/lcd/ultralcd.cpp:1451:46: note: in expansion of macro '_PID_MENU_ITEMS'
       #define PID_MENU_ITEMS(HLABEL, hindex) _PID_MENU_ITEMS(HLABEL, hindex)
                                              ^
sketch/module/lcd/ultralcd.cpp:1454:5: note: in expansion of macro 'PID_MENU_ITEMS'
     PID_MENU_ITEMS("", 0);
     ^
exit status 1
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
fix it!!
