### ISSUE TITLE
ERROR LANGUAGE

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#131]
LCD_LANGUAGE!!??

Arduino: 1.6.7 (Mac OS X), Placa:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch/base.h:42:0,
                 from /Users/brenosouza/Downloads/MarlinKimbra-master-44/MK/MK.ino:198:
sketch/module/sanitycheck.h:178:6: error: #error DEPENDENCY ERROR: Missing setting LANGUAGE_CHOICE
     #error DEPENDENCY ERROR: Missing setting LANGUAGE_CHOICE
      ^
exit status 1
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
Thx... Fix it!!!
