### ISSUE TITLE
issue of g29

### ISSUE THREAD

**Issue by whyucome** [MagoKimbra/MarlinKimbra#132]
I use new ver4.2.81and base setting(raise20.grid 11)when i use g29,it go to last three point then report endpoint hit Z. Anyone has this issue??

**Comment by MagoKimbra** [comment]
Mechanism? Cartesian, Delta, Core??

**Comment by whyucome** [comment]
Delta and use Z-probe

**Comment by MagoKimbra** [comment]
Ok put raise between probe to 30... I working for fix it...

**Comment by whyucome** [comment]
Ok. I will test it later. Thx

**Comment by whyucome** [comment]
Still report error
