### ISSUE TITLE
MK4DUE not compiled.

### ISSUE THREAD

**Issue by pirat777knj** [MagoKimbra/MarlinKimbra#141]
Greetings. All good!
I Bought Arduino Due. But Marlin Kimbra firmware compiles a bunch of errors. That is not compiled at all. How do I fix this?

`
******************************************************
sketch\module\lcd\ultralcd_st7920_u8glib_rrd.h:109:7: note: in expansion of macro 'ST7920_NCS'

       ST7920_NCS();

       ^

sketch\module\lcd\ultralcd_st7920_u8glib_rrd.h:33:25: error: 'LCD_PINS_RS' was not declared in this scope

 #define ST7920_CS_PIN   LCD_PINS_RS

                         ^

sketch\module\lcd\ultralcd_st7920_u8glib_rrd.h:55:50: note: in expansion of macro 'ST7920_CS_PIN'

   #define ST7920_CS()              {digitalWrite(ST7920_CS_PIN, 1);u8g_10MicroDelay();}

                                                  ^

sketch\module\lcd\ultralcd_st7920_u8glib_rrd.h:120:7: note: in expansion of macro 'ST7920_CS'

       ST7920_CS();

       ^

sketch\module\lcd\ultralcd_st7920_u8glib_rrd.h:33:25: error: 'LCD_PINS_RS' was not declared in this scope

 #define ST7920_CS_PIN   LCD_PINS_RS

                         ^

sketch\module\lcd\ultralcd_st7920_u8glib_rrd.h:56:50: note: in expansion of macro 'ST7920_CS_PIN'

   #define ST7920_NCS()             {digitalWrite(ST7920_CS_PIN, 0);}

                                                  ^

sketch\module\lcd\ultralcd_st7920_u8glib_rrd.h:135:7: note: in expansion of macro 'ST7920_NCS'

       ST7920_NCS();

       ^

exit status 1`

**Comment by MagoKimbra** [comment]
The link error is broke...

Date: Mon, 30 May 2016 13:32:33 -0700

**Comment by pirat777knj** [comment]
[errors.txt](https://github.com/MagoKimbra/MarlinKimbra/files/291137/errors.txt)

Here is the complete error log .

**Comment by MagoKimbra** [comment]
Ok you must setting ide warning to none. Go in setting Arduino ide and setting warning to none....
Do you what display set??

**Comment by pirat777knj** [comment]
Yes. Reprap fullgraphic smart controller + adapter 5V-3.3V.

**Comment by MagoKimbra** [comment]
The Display Fullgraphic is not supported for all cards Arduino due.
Have you card?

**Comment by pirat777knj** [comment]
of course I have. but even with the flashing turn off the display gives an error (

**Comment by pirat777knj** [comment]
You say that the display is not supported. But on firmware Repetier Firmware it works. True adapter.
![img_2016-06-03_155252_hdr 1](https://cloud.githubusercontent.com/assets/19655506/15779204/993d93fe-29a3-11e6-85a9-018175ce383c.jpg)

**Comment by MagoKimbra** [comment]
No I meant in MK4due, I have not the right pin for the display of all the cards.
If you have pin write me and i add this in firmware!!!

**Comment by pirat777knj** [comment]
If you need the pin numbers on the board Due corresponding conclusions of the display, here:
according to the scheme:
[http://forums.reprap.org/file.php?249,file=49666,filename=RRD_FULL_GRAPHIC_SMART_CONTROLER_SCHEMATIC.pdf,download=1](url)
As well as the scheme:
[http://www.reprap.org/mediawiki/images/3/3f/Arduinomegapololushieldschematic.png](url)

>LCD RW pin 16
>LCD RS pin 17
>LCD E pin 23

Checked multimeter. All correspondence. Also, I decided to write conclusions for thermistors.

> #define TEMP_0_PIN         9   
> #define TEMP_1_PIN         10 

Download the latest update, for some reason, was to swear:

> In file included from sketch\base.h:51:0,

                 from C:\Users\tj\Desktop\MK4due\MK4due.ino:210:

sketch\module/sanitycheck.h:592:8: error: #error DEPENDENCY ERROR: Missing setting Z_RAISE_BEFORE_HOMING

       #error DEPENDENCY ERROR: Missing setting Z_RAISE_BEFORE_HOMING

        ^

exit status 1
Ошибка компиляции для платы Arduino Due (Programming Port).
