### ISSUE TITLE
AUTO BED LEVELING ISSUE

### ISSUE THREAD

**Issue by jgauchia** [MagoKimbra/MarlinKimbra#143]
If AUTO_BED_LEVELING_FEATURE was enabled and MIN_Z_HEIGHT_FOR_HOMING wasn't enabled sanitycheck raise this error: (from 4.2.82 to 4.2.84)

_sketch/module/sanitycheck.h:1954:6: error: #error "Z_RAISE_BEFORE_HOMING is deprecated. Use MIN_Z_HEIGHT_FOR_HOMING instead."
     #error "Z_RAISE_BEFORE_HOMING is deprecated. Use MIN_Z_HEIGHT_FOR_HOMING instead."_

When MIN_Z_HEIGHT_FOR_HOMING was defined and Z_RAISE_BEFORE_HOMING was undefined sanitycheck raise this error:

_sketch/module/sanitycheck.h:592:8: error: #error DEPENDENCY ERROR: Missing setting Z_RAISE_BEFORE_HOMING
       #error DEPENDENCY ERROR: Missing setting Z_RAISE_BEFORE_HOMING_

this has no logic

**Comment by MagoKimbra** [comment]
Fix it!

**Comment by jgauchia** [comment]
Thx!!! 
Sorry for the other Issue
