### ISSUE TITLE
AUTO BED LEVELING ISSUE (2) - gcode_G28()

### ISSUE THREAD

**Issue by jgauchia** [MagoKimbra/MarlinKimbra#145]
From 4.2.82 to 4.2.84
When #define MIN_Z_HEIGHT_FOR_HOMING  and undefined Z_RAISE_BEFORE_HOMING compile error.

_sketch/module/MK_Main.cpp: In function 'void gcode_G28()':
sketch/module/MK_Main.cpp:3884:37: error: 'Z_RAISE_BEFORE_HOMING' was not declared in this scope
             destination[Z_AXIS] = -(Z_RAISE_BEFORE_HOMING) * home_dir(Z_AXIS);  // Set destination away from bed_

**Comment by jgauchia** [comment]
Maybe changing Z_RAISE_BEFORE_HOMING with MIN_Z_HEIGHT_FOR_HOMING in MK_Main works. I'll try it

**Comment by MagoKimbra** [comment]
Ok i fix it!!!
Thx....

**Comment by jgauchia** [comment]
Well I've changed but still compile errors, Can you reopen the issue and post them?
I'm current testing this part of firmware , If you need some feedback from my..

**Comment by MagoKimbra** [comment]
Chek now!

**Comment by jgauchia** [comment]
Checked. New Issue for me , sorry :(
