### ISSUE TITLE
Online configurator issue

### ISSUE THREAD

**Issue by markusrudolf** [MagoKimbra/MarlinKimbra#155]
Sorry for posting here, I made a comment already on http://www.marlinkimbra.it, but theres no way to contact the maintainer directly (at least I didn't find any)

I have problems with the online configurator. I build myself a core XY printer with a dual Z Axis Stepper (2 Drivers on RAMPS). It’s not possible to select Dual Z on the “mechanics” page as soon as you select printer type “core” on the first page.

I fixed it manually for now, but it would be good to have it fixed upstream so I could re-upload my config for making additional tweaks.

Markus

**Comment by MagoKimbra** [comment]
Add!
