### ISSUE TITLE
PID Autotune Menu

### ISSUE THREAD

**Issue by pasmont** [MagoKimbra/MarlinKimbra#164]
Buongiorno Mago.
Innanzitutto grazie per il lavoro che tu e tutti gli altri contributors fate ogni giorno.
Uso MarlinKimbra su una stampante cartesiana "Prusa-like" con display LCD RepRapDiscount Smart Controller. Dalla versione 4.2.87_dev ho avuto problemi di compilazione attivando il PID Autotune Menu. L'IDE segnalava questo errore:
sketch\src\lcd\ultralcd.cpp:1718:130: error: macro "ARRAY_BY_HOTENDS" passed 4 arguments, but takes just 1
            const int heater_maxtemp[HOTENDS] = ARRAY_BY_HOTENDS(HEATER_0_MAXTEMP, HEATER_1_MAXTEMP, HEATER_2_MAXTEMP, HEATER_3_MAXTEMP);

sketch\src\lcd\ultralcd.cpp:1717:57: error: 'ARRAY_BY_HOTENDS1' was not declared in this scope
            int autotune_temp[HOTENDS] = ARRAY_BY_HOTENDS1(150);

sketch\src\lcd\ultralcd.cpp:1718:43: error: 'ARRAY_BY_HOTENDS' was not declared in this scope
            const int heater_maxtemp[HOTENDS] = ARRAY_BY_HOTENDS(HEATER_0_MAXTEMP, HEATER_1_MAXTEMP, HEATER_2_MAXTEMP, HEATER_3_MAXTEMP);

Immagino si tratti di un refuso in ultralcd.cpp dopo la riscrittura di alcune funzioni nella versione 4.2.87_dev.
Credo di aver risolto modificando le righe di codice 1728 e 1729 in ultralcd.cpp della versione 4.2.88_dev
da:
      int autotune_temp[HOTENDS] = ARRAY_BY_HOTENDS1(150);
      const int heater_maxtemp[HOTENDS] = ARRAY_BY_HOTENDS(HEATER_0_MAXTEMP, HEATER_1_MAXTEMP, HEATER_2_MAXTEMP, HEATER_3_MAXTEMP);

a
      int autotune_temp[HOTENDS] = ARRAY_BY_HOTENDS(150);
      const int heater_maxtemp[HOTENDS] = ARRAY_BY_HOTENDS_N(HEATER_0_MAXTEMP, HEATER_1_MAXTEMP, HEATER_2_MAXTEMP, HEATER_3_MAXTEMP);

Spero sia corretto, non sono un programmatore.
Grazie ancora

**Comment by MagoKimbra** [comment]
Ok corretto... Grazie mille!!!!
