### ISSUE TITLE
avr/io.h missing

### ISSUE THREAD

**Issue by jmlcatarino** [MagoKimbra/MarlinKimbra#174]
Hi there, I'm trying to upload this firmware to a Due and it gives me this error : sketch/src/HAL/fastio.h:31:20: fatal error: avr/io.h: No such file or directory
 #include <avr/io.h>

I can't find any solutions for this error. I was using the earlier version, MK4Due and it gave lot's of errors with LCD settings, by not recognizing several parts of the code, so I'm trying this new version. Using IDE 1.8.3
Thank you in advance

**Comment by MagoKimbra** [comment]
This Firmware is old and only for 8 bit processor...
Look https://github.com/MKFirmware/MK4duo

**Comment by jmlcatarino** [comment]
I thought it was the newer version. I went to your site and got the idea that it was newer than MK4duo. :) Thanks anyway and a special thanks for the firmware.
