### ISSUE TITLE
Issue with thermal protection 

### ISSUE THREAD

**Issue by EPES-Rades** [MagoKimbra/MarlinKimbra#181]
I would like to ask you about issue thermal protection. For example: If I disconnect thermisto of bed, printer write:

Error:MINTEMP triggered, system stopped! Heater_ID: Bed
[ERROR] Error:MINTEMP triggered, system stopped! Heater_ID: Bed

Error:Printer halted. kill() called!
[ERROR] Error:Printer halted. kill() called!

but the bed still heating. Same issue with heater.
I tried to change below parametrs but without result:

#define INVERTED_HEATER_PINS false
#define INVERTED_BED_PIN false

#define THERMAL_PROTECTION_HOTENDS true
#define THERMAL_PROTECTION_BED true

I use arduino due with ramps-fd_v1.

Thank you for your answere / help.

Radek B.

**Comment by MagoKimbra** [comment]
This firmware is old. Please go to https://github.com/MKFirmware/MK4duo for new firmware..

**Comment by EPES-Rades** [comment]
Ok, thank you for answer.
I have downloaded the newest firmware V4.3.4. I'll try it. I had the firmware V4.3.2.

I'm sorry. I choose wrong "Issues" branch.
