### ISSUE TITLE
error "need tuning pid" after upgrade at last version

### ISSUE THREAD

**Issue by demonbd** [MagoKimbra/MarlinKimbra#185]
Hi after upload the last version made by "MK4duo - Firmware configurator tool (Rev 4.1.5) - Firmware Version 4.3.6", on print heating bed i receive this error "need tuning pid", but the parameter it's the same of old release.

regards

**Comment by MagoKimbra** [comment]
Ok, you know that the parameters are right, but the firmware does not. So I do the pid tune or put them manually with the M301 command and then save with m500

**Comment by demonbd** [comment]
[MK4duo.zip](https://github.com/MKFirmware/MarlinKimbra/files/1978006/MK4duo.zip)

**Comment by demonbd** [comment]
thank's for fast response.

**Comment by demonbd** [comment]
on the zip found the conf. files

**Comment by demonbd** [comment]
Ciao MagoKimbra , e possibile comunicare in Italiano eventualmente hai una mail ? 

ciao
Davide
