### ISSUE TITLE
Configuration.h problema di codifica

### ISSUE THREAD

**Issue by simone97** [MagoKimbra/MarlinKimbra#24]
Salve,
con la nuova versione di arduino IDE 1.6.1 ho riscontrato il seguente avviso di compilazione:
"Configuration.h" contiene caratteri non riconosciuti. Se questo codice è stato creato con una vecchia versione di Arduino potresti dover usare il comando "Strumenti->Correggi codifica e ricarica" per aggiornare lo sketch. In caso contrario, per eliminare questo avviso, devi cancellare i caratteri non supportati dallo sketch."

Con Notepad++ ho convertito la codifica in ANSI e poi nuovamente in UTF-8 senza BOM e il problema si è risolto.
Credo che sia necessario aggiornare la codifica del file presente nella repository.

PS: Scrivo direttamente in italiano dato che è un problema banale e mi sembrava inutile riportarlo scrivendoti in inglese
Cordiali Saluti,
Simone

**Comment by MagoKimbra** [comment]
Grazie Simone, appena torno a casa aggiusto...

Date: Sat, 21 Mar 2015 05:28:59 -0700
