### ISSUE TITLE
pins2tool.h

### ISSUE THREAD

**Issue by simone97** [MagoKimbra/MarlinKimbra#30]
Salve,
a cosa dovrebbe servire questo file?
Attualmente se tenuto in compilazione sovrascrive il pin della ventola impedendone il funzionamento.
Saluti,
Simone

**Comment by MagoKimbra** [comment]
Quel file serve per il tools di configurazione online... Le righe alla fine non ci dovevano essere, è la mia configurazione, le ho pulite... grazie ancora...

Date: Wed, 1 Apr 2015 14:03:00 -0700

**Comment by simone97** [comment]
Perfetto,
Chiudo
