### ISSUE TITLE
#define PIDTEMPBED - ERROR

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#42]
Arduino: 1.6.3 (Mac OS X), Placa:"Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

ConfigurationStore.cpp:744:33: error: macro "ECHO_SMV" requires 4 arguments, but only 2 given
       ECHO_SMV("  M304 P", bedKp); // for compatibility with hosts, only echos values for E0
                                 ^
ConfigurationStore.cpp: In function 'void Config_PrintSettings(bool)':
ConfigurationStore.cpp:744:7: error: 'ECHO_SMV' was not declared in this scope
       ECHO_SMV("  M304 P", bedKp); // for compatibility with hosts, only echos values for E0
       ^
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
Thx i fix
