### ISSUE TITLE
Thermal Runaway Protection - ERROR

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#43]
Arduino: 1.6.3 (Mac OS X), Placa:"Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

temperature.cpp:1089:44: error: macro "ECHO_S" passed 2 arguments, but takes just 1
         ECHO_S(ER, MSG_THERMAL_RUNAWAY_STOP);
                                            ^
temperature.cpp: In function 'void thermal_runaway_protection(TRState*, millis_t*, float, float, int, int, int)':
temperature.cpp:1089:9: error: 'ECHO_S' was not declared in this scope
         ECHO_S(ER, MSG_THERMAL_RUNAWAY_STOP);
         ^
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
Thx i fix
