### ISSUE TITLE
Delta dual extruder Bug

### ISSUE THREAD

**Issue by Dougwar** [MagoKimbra/MarlinKimbra#52]
I noticed that Marlin has one bug for dual extruder in deltas

please check these links:

http://forums.reprap.org/read.php?178,300903

https://groups.google.com/forum/#!topic/deltabot/foGyIqCf2bs

Thanks

**Comment by Dougwar** [comment]
did you read this?

**Comment by MagoKimbra** [comment]
Yes i read this... But i do not understand the problem..
I have tested on my MarlinKimbra and not see problem..

**Comment by Dougwar** [comment]
Thanks for the answer.
I'm trying to print with dual extruders in my delta, when the tool change T0 to T1 or any change, the hotend go up and lost reference, it go up for every tool change. If you still don't understand I can make a video with the problem, just let me know.
Thanks

**Comment by MagoKimbra** [comment]
Ok i retest this..

**Comment by MagoKimbra** [comment]
I retest on my delta and haven't problem...
Please send me your configuration.h and configuration_delta.h
