### ISSUE TITLE
quando descomenta #define SHOW_TEMP_ADC_VALUES

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#73]
Arduino: 1.6.4 (Mac OS X), Placa:"Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from base.h:54:0,
                 from Marlin_main.cpp:30:
Marlin_main.cpp: In function 'void gcode_M105()':
Marlin_main.cpp:5152: error: 'OVERSAMPLENR' was not declared in this scope
       ECHO_MV("C->", rawBedTemp()/OVERSAMPLENR, 0);
                                   ^
comunication.h:47:51: note: in definition of macro 'SERIAL_PRINT'
 #define SERIAL_PRINT(msg, args...) MYSERIAL.print(msg, ##args)
                                                   ^
Marlin_main.cpp:5152:7: note: in expansion of macro 'ECHO_MV'
       ECHO_MV("C->", rawBedTemp()/OVERSAMPLENR, 0);
       ^
'OVERSAMPLENR' was not declared in this scope

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
Thank's
I fix it!!!
