### ISSUE TITLE
to delta too slow processing

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#74]
for this very delta processing. when he makes a circle he is waging before in older versions it not empty

**Comment by simonepri** [comment]
Can you provide more info about this?
Or just explain better your problem.
Thanks

**Comment by prophetmaster** [comment]
i have the bug with my delta it give brake in displacement, i have 120 delta segments per second and the bug is still here...

**Comment by prophetmaster** [comment]
the big problem from Marlin is calculation Repetier calculate in step not in float ! this is the right solution solution for me...

**Comment by MagoKimbra** [comment]
Explain me please..

**Comment by prophetmaster** [comment]
move stop move stop, do not move linear the cpu overflow when calculate displacement...
