### ISSUE TITLE
DELTA SEGMENTS FOR MM!? NÃO FUNCIONA

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#75]
/ Make delta curves from many straight lines (linear interpolation).
// This is a trade-off between visible corners (not enough segments)
// and processor overload (too many expensive sqrt calls).
// The new function do not use segments per second but segments per mm
// if you want use new function comment this (using // at the start of the line)
// #define DELTA_SEGMENTS_PER_SECOND 150

**Comment by MagoKimbra** [comment]
It is in this function tests...
