### ISSUE TITLE
ERROR AO DESCOMENTAR #define SDSUPPORT

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#76]
Arduino: 1.6.4 (Mac OS X), Placa:"Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Opções de compilação alteradas, recompilando tudo
In file included from conditionals.h:217:0,
                 from base.h:51,
                 from cardreader.cpp:1:
pins.h:898: error: expected unqualified-id before numeric constant
   #define SDSS                    53
                                   ^
pins.h:5134:29: note: in expansion of macro 'SDSS'
   #define SS_PIN            SDSS
                             ^
Sd2PinMap.h:44:15: note: in expansion of macro 'SS_PIN'
 uint8_t const SS_PIN = 53;    // B0
               ^
expected unqualified-id before numeric constant

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
Ok fix!!
