### ISSUE TITLE
LCD compile error

### ISSUE THREAD

**Issue by Trvorts** [MagoKimbra/MarlinKimbra#83]
ultralcd.cpp.o: In function `_lcd_move':
C:\Users\Trvorts\AppData\Local\Temp\build8714360466396254804.tmp/ultralcd.cpp:986: undefined reference to `refresh_cmd_timeout()'

**Comment by Trvorts** [comment]
RAMPS board with RepRapDiscount Smart Controler

**Comment by simonepri** [comment]
related issue #81
