### ISSUE TITLE
ERROR!!

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#89]
Arduino: 1.6.4 (Mac OS X), Placa:"Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from blinkm.cpp:5:0:
base.h:50:31: fatal error: language/language.h: No such file or directory
 #include "language/language.h"
                               ^
compilation terminated.
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
You must use arduino ide 1.6.7 for compiling...
