### ISSUE TITLE
Nextion causing RAMPS 1.4 to reset

### ISSUE THREAD

**Issue by AllenMcAfee** [MagoKimbra/MarlinKimbra#90]
I am trying to implement the Nextion/MK firmware on my RAMPS 1.4 and am running into a reset issue.  When running just the Nextion and a thermister it will stay on all day, but once I have the RAMPS board fully wired up with an ATX power supply, it starts to do a continual reset after 20 seconds.  I've removed just about everything I can think of, but maybe someone has a PWM issue they've already troubleshot.  I've tried a separate powersupply for just the LCD, but this configuration doesn't read the serial data coming from the Arduino.

Thoughts?

**Comment by MagoKimbra** [comment]
disabled PS_DEFAULT_OFF.
