### ISSUE TITLE
Bed PID autotune 

### ISSUE THREAD

**Issue by redsqrly** [MagoKimbra/MarlinKimbra#92]
Hey! Im trying to set my bed PID, but no matter what command i try it always does the autotune on the hotend. Am i missing something? Ive tried M303 E-1 SXXX, M303 SXXX, M303 E1 SXXX C8... But all of them heat up the extruder only.

**Comment by MagoKimbra** [comment]
I.. Use H not E... M303 H<hotend> S, for bedthe command is M303 H-1

**Comment by redsqrly** [comment]
Ahh! Thanks a lot for the quick reply, much appreciated!

**Comment by MagoKimbra** [comment]
Ok Close!!!
