### ISSUE TITLE
error #define BABYSTEPPING

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra#96]
Arduino: 1.6.7 (Mac OS X), Placa:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch/base.h:38:0,
                 from /Users/brenosouza/Downloads/MarlinKimbra-master-31/MK/MK.ino:192:
sketch/module/sanitycheck.h:500:8: error: #error DEPENDENCY ERROR: Missing setting BABYSTEP_Z_MULTIPLICATOR
       #error DEPENDENCY ERROR: Missing setting BABYSTEP_Z_MULTIPLICATOR
        ^
exit status 1
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
THX fix...
