### ISSUE TITLE
Not compile sketch

### ISSUE THREAD

**Issue by Deepoff** [MagoKimbra/MarlinKimbra#97]
C:\DOCUME~1\*****\LOCALS~1\Temp\build92b315221a45dac1da7e7fb9e76d9964.tmp/core\core.a(main.cpp.o): In function `main':

D:\distr\Free_Soft\Programming\arduino-1.6.6\hardware\arduino\avr\cores\arduino/main.cpp:37: undefined reference to `setup'

D:\distr\Free_Soft\Programming\arduino-1.6.6\hardware\arduino\avr\cores\arduino/main.cpp:47: undefined reference to `loop'

collect2.exe: error: ld returned 1 exit status

exit status 1

Trying to compile the project.

**Comment by MagoKimbra** [comment]
you must have arduino ide 1.6.7.
